Blog.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Blog.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Blog.Repo;
using Blog.Data.Models;
using Blog.Service;
using Microsoft.AspNetCore.Http;
using System.IO;
using ContosoUniversity;
using ReflectionIT.Mvc.Paging;

namespace Blog.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;
        private readonly ApplicationContext _appContext;
        private readonly UserManager<ApplicationUser> _userManager;
        public ArticleController(IArticleService articleService, ICommentService commentService, UserManager<ApplicationUser> userManager, ApplicationContext appContext)
        {
            this._articleService = articleService;
            this._commentService = commentService;
            this._userManager = userManager;
            this._appContext = appContext;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var qry = _appContext.Article.AsNoTracking().OrderByDescending(p => p.DateCreate);
            var model = await PagingList.CreateAsync(qry, 5, page);
            return View(model);
        }

        public IActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(ArticleModel model, IFormFile thumb)
        {
            if (ModelState.IsValid)
            {

                Article article = new Article
                {
                    Thumbnail = Path.GetExtension(thumb.FileName),
                    Title = model.Title,
                    Content = model.Content,
                    UserId = _userManager.GetUserId(User),
                    DateCreate = DateTime.Now,
                };
                _articleService.InsertArticle(article);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", $"{article.Id}{article.Thumbnail}");
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await thumb.CopyToAsync(stream);
                }


                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ArticleDetail(Int64 id)
        {
            Article article = _articleService.GetArticle(id);

            if (article == null)
            {
                return NotFound();
            }
            ViewBag.UserId = _userManager.GetUserId(User);
            var a = article.UserId;
            return View(article);

        }
        public IActionResult Edit(Int64 id)
        {
            Article article = _articleService.GetArticle(id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("ArticleID,Title,Content")] Article model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Article article = new Article
                    {
                        Id = model.Id,
                        Title = model.Title,
                        Content = model.Content,
                    };
                    _articleService.UpdateArticle(article);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleModelExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Delete(Int64 id)
        {
            _articleService.DeleteArticle(_articleService.GetArticle(id));
            return View("Index", _articleService.GetArticle());
        }
        private bool ArticleModelExists(Int64 id)
        {
            return _articleService.GetArticle(id) != null;
        }


    }
}

Blog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>

   
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/swipebox.css" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <div class="container">
            <div class="header-info">
                <div class="logo">
                    <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" /> </a>
                </div>
                <div class="logo-right">
                    <span class="menu"><img src="~/images/menu.png" alt=" " /></span>
                    <ul class="nav1">

                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Article" asp-action="Upload">Upload</a></li>
                        <li><a asp-area="" asp-controller="Article" asp-action="Index">Articles</a></li>
                    </ul>
                     @await Html.PartialAsync("_LoginPartial");
                </div>
                <div class="clearfix"> </div>
               
            </div>
        </div>
    </div>
    <!-- header -->
    <!-- content -->
    <div class="content">
        <div class="container">
            <div class="content-text">


                <div class="title">
                    @RenderBody()
                    
                </div>
                <div class="categories">
                    <div class="categ">
                        <div class="cat">
                            <h3>Categories</h3>
                            <ul>
                                
                            </ul>
                        </div>
                        <div class="recent-com">
                            <h3>Recent Comments</h3>
                            <ul>
                                
                            </ul>
                        </div>
                        <div class="view">
                          
                        </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- //content -->
    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="footer-grids">
                <div class="footer-grid">
                    <h3>About Us</h3>
                    <p>
                       Team MS
                    </p>
                </div>
                <div class="footer-grid">
                    <h3>Site Page</h3>
                    <ul>
                        <li class="cap1"><a href="index.html">Home</a></li>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="articles.html">Gallery</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>Praesent pharetra</h3>
                    <ul>
                        
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p>Template by<a href="http://w3layouts.com/"> w3layouts</a></p>
        </div>
    </div>
    @RenderSection("Scripts", required: false)
   
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/easing.js"></script>

    <script src="~/js/jquery.mixitup.min.js"></script>
    <script src="~/js/jquery.swipebox.min.js"></script>
    <script src="~/js/move-top.js"></script>


</body>
</html>